name: VoteStaff
author: MariusB
version: 1.0.0
main: MariusB\VoteStaff\VoteStaff
api: 1.12.0

commands:
    v:
        description: Vote for a player to be staff on server.
        permission: votestaff.command
        
permissions:
    votestaff.command:
        description: Permission for all vote commands.
        default: true
    votestaff.command.staff:
        description: Permission for /vote staff command.
        default: true
